# Generated by Django 4.1.3 on 2022-11-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('scode', models.CharField(max_length=10)),
                ('credit', models.IntegerField()),
            ],
        ),
    ]
